- name: >
    Debian | set_fact
      postfix_supported_os: True
  set_fact:
    postfix_supported_os: True

- name: Install ntpdate
  package:
    name:
      - libsasl2-modules
      - postfix
    state: present
